@url = http://localhost:3000
 
### ADD A NOTE
POST {{url}}/api/add-note
content-type: application/json
 
{
    "app_pin": "1234",
    "body": "Das ist die erste notiz",
    "rank": 2.2
}

### GET ALL NOTES
POST {{url}}/api/get-notes